# Generated by Django 3.2.9 on 2022-03-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned_till',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='perma_banned',
            field=models.BooleanField(default=False),
        ),
    ]
