# Generated by Django 3.2.9 on 2021-12-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
