# Generated by Django 3.2.9 on 2021-11-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='color',
            field=models.TextField(default='#000000'),
            preserve_default=False,
        ),
    ]
