# Generated by Django 3.2.9 on 2022-02-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomtype_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='type',
            new_name='typeId',
        ),
    ]
