# Generated by Django 3.2.9 on 2022-02-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_rename_type_room_typeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=24),
        ),
    ]
