# Generated by Django 3.2.9 on 2022-02-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20220202_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='typeId',
            new_name='type_id',
        ),
    ]
