# Generated by Django 3.2.9 on 2022-02-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_rename_type_id_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='color',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=24),
        ),
    ]
