# Generated by Django 3.2.9 on 2022-03-01 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 1, 15, 5, 4, 8792, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 1, 15, 5, 12, 945964, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
