class ErrorType():
  USERNAME_TAKEN = 'USERNAME_TAKEN'
  EMAIL_TAKEN = 'EMAIL_TAKEN'
  PASSWORD_TOO_SIMPLE = 'PASSWORD_TOO_SIMPLE'
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT'
  PASSWORD_NUMERIC = 'PASSWORD_NUMERIC'
  EMAIL_INCORRECT = 'EMAIL_INCORRECT'
  USER_NOT_FOUND = 'USER_NOT_FOUND'
  TOKEN_EXPIRED = 'TOKEN_EXPIRED'
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'
  NOT_AUTHENTICATED = 'NOT_AUTHENTICATED'
  

def get_error_dict(errorType, msg):
  return {'type': errorType, 'message': msg}
